# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decision.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.baslik = QtWidgets.QLabel(self.centralwidget)
        self.baslik.setGeometry(QtCore.QRect(180, 20, 291, 71))
        self.baslik.setObjectName("baslik")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 201, 221))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_ogr_giris = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ogr_giris.sizePolicy().hasHeightForWidth())
        self.Btn_ogr_giris.setSizePolicy(sizePolicy)
        self.Btn_ogr_giris.setMouseTracking(False)
        self.Btn_ogr_giris.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Btn_ogr_giris.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Btn_ogr_giris.setObjectName("Btn_ogr_giris")
        self.verticalLayout_2.addWidget(self.Btn_ogr_giris)
        self.Btn_ogrtmn_giris = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ogrtmn_giris.sizePolicy().hasHeightForWidth())
        self.Btn_ogrtmn_giris.setSizePolicy(sizePolicy)
        self.Btn_ogrtmn_giris.setObjectName("Btn_ogrtmn_giris")
        self.verticalLayout_2.addWidget(self.Btn_ogrtmn_giris)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 140, 191, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 171, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_ogr_kayit = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_ogr_kayit.sizePolicy().hasHeightForWidth())
        self.Btn_ogr_kayit.setSizePolicy(sizePolicy)
        self.Btn_ogr_kayit.setObjectName("Btn_ogr_kayit")
        self.verticalLayout_3.addWidget(self.Btn_ogr_kayit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baslik.setText(_translate("MainWindow", "Quiz Sistemi"))
        self.groupBox.setTitle(_translate("MainWindow", "Giriş yap"))
        self.Btn_ogr_giris.setText(_translate("MainWindow", "Öğrenci"))
        self.Btn_ogrtmn_giris.setText(_translate("MainWindow", "Öğretmen "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kayıt ol"))
        self.Btn_ogr_kayit.setText(_translate("MainWindow", "Öğrenci "))
